// GENERATED by scripts/gen-universe.mjs — do not edit by hand.
// Source: https://synthetick.org/v1/universe/robinhood + GeckoTerminal V3 pool discovery (2026-08-03).
// Tradable = Uniswap V3 USDG pool with reserve >= $15000.
import type { Address } from "@sail.money/sailor/sdk";

export interface TradableAsset {
  symbol: string;
  name: string;
  token: Address;
  decimals: number;
  pool: Address;      // the USDG/<token> V3 pool — also the mandate's reference pool
  feeTier: number;    // Uniswap V3 fee, hundredths of a bip (3000 = 0.30%)
}

export const CHAIN_ID = 4663;
export const USDG: Address = "0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168";
export const USDG_DECIMALS = 6;
export const WETH: Address = "0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73";

// Canonical Uniswap V3 on Robinhood Chain (verified on-chain: pool.factory()
// matches, quoter.WETH9() matches the chain's WETH).
export const UNIV3_FACTORY: Address = "0x1f7d7550B1b028f7571E69A784071F0205FD2EfA";
export const SWAP_ROUTER_02: Address = "0xCaf681a66D020601342297493863E78C959E5cb2";
export const QUOTER_V2: Address = "0x33e885eD0Ec9bF04EcfB19341582aADCb4c8A9E7";

export const TRADABLE: TradableAsset[] = [
  {
    "symbol": "NVDA",
    "name": "NVIDIA",
    "token": "0xd0601CE157Db5bdC3162BbaC2a2C8aF5320D9EEC" as Address,
    "decimals": 18,
    "pool": "0xd4eb21209c4d6093f80b5b84f5c45cc093ea14a3" as Address,
    "feeTier": 500
  },
  {
    "symbol": "SPCX",
    "name": "Space Exploration Technologies Corp. Class A Common Stock",
    "token": "0x4a0E65A3EcceC6dBe60AE065F2e7bb85Fae35eEa" as Address,
    "decimals": 18,
    "pool": "0xeb07d9587efd1778dfb9c385ec43ef6d5f9fe401" as Address,
    "feeTier": 3000
  },
  {
    "symbol": "GME",
    "name": "GameStop",
    "token": "0x1b0E319c6A659F002271B69dB8A7df2F911c153E" as Address,
    "decimals": 18,
    "pool": "0xe2b46c905e12ab8e2f864e4821a4325884c1b126" as Address,
    "feeTier": 500
  },
  {
    "symbol": "SPY",
    "name": "SPDR S&P 500 ETF Trust",
    "token": "0x117cc2133c37B721F49dE2A7a74833232B3B4C0C" as Address,
    "decimals": 18,
    "pool": "0xa43b424bc609495aed4bcd88d654934b510b0ad9" as Address,
    "feeTier": 3000
  },
  {
    "symbol": "SLV",
    "name": "iShares Silver Trust",
    "token": "0x411eFb0E7f985935DAec3D4C3ebaEa0d0AD7D89f" as Address,
    "decimals": 18,
    "pool": "0x0fa7bc480885dcf58ad2ef63ec7289cf2481d51c" as Address,
    "feeTier": 10000
  },
  {
    "symbol": "AAPL",
    "name": "Apple",
    "token": "0xaF3D76f1834A1d425780943C99Ea8A608f8a93f9" as Address,
    "decimals": 18,
    "pool": "0x783c9bbb765047cfdd2b84b92b2ca9f11d34b7ed" as Address,
    "feeTier": 3000
  },
  {
    "symbol": "COST",
    "name": "Costco",
    "token": "0x4EA005168D7F09a7A0Ba9D1DEf21a479950E44C2" as Address,
    "decimals": 18,
    "pool": "0x0a2121a50a09ed0796ae81f9c53ff9398355a398" as Address,
    "feeTier": 3000
  },
  {
    "symbol": "USO",
    "name": "United States Oil Fund",
    "token": "0xa30FA36Db767ad9eD3f7a60fC79526fB4d56D344" as Address,
    "decimals": 18,
    "pool": "0x6ed11c7dfd8e2ca5620eed29a7b9b53ae90dd0d2" as Address,
    "feeTier": 10000
  },
  {
    "symbol": "QQQ",
    "name": "Invesco QQQ",
    "token": "0xD5f3879160bc7c32ebb4dC785F8a4F505888de68" as Address,
    "decimals": 18,
    "pool": "0xebd78dcfc8a6b3a696f1e191ad1ff321f9579f79" as Address,
    "feeTier": 3000
  },
  {
    "symbol": "TSLA",
    "name": "Tesla",
    "token": "0x322F0929c4625eD5bAd873c95208D54E1c003b2d" as Address,
    "decimals": 18,
    "pool": "0xf4acdaeeb7022862a763c9b1b885e11191c889e3" as Address,
    "feeTier": 3000
  },
  {
    "symbol": "RDDT",
    "name": "Reddit",
    "token": "0x05b37Fb53A299a1b874A619e1c4C404D52C36F4C" as Address,
    "decimals": 18,
    "pool": "0xa8744e76aed23b05f0126335e7bd38f7935d19fe" as Address,
    "feeTier": 10000
  },
  {
    "symbol": "MSFT",
    "name": "Microsoft",
    "token": "0xe93237C50D904957Cf27E7B1133b510C669c2e74" as Address,
    "decimals": 18,
    "pool": "0xeb60bcd1d920ad6e102690ccfc6fb488899e1510" as Address,
    "feeTier": 3000
  },
  {
    "symbol": "NFLX",
    "name": "Netflix",
    "token": "0xE0444EF8BF4eD74f74FD73686e2ddF4C1c5591E8" as Address,
    "decimals": 18,
    "pool": "0xea75ea625d83ae276b9ae8b0a3dc205916ee65cf" as Address,
    "feeTier": 10000
  },
  {
    "symbol": "DELL",
    "name": "Dell",
    "token": "0x941AE714EC6D8130c7B75d67160Ca08f1e7d11Dd" as Address,
    "decimals": 18,
    "pool": "0xc30c89cb7815a1488b7998d15eec73961707fc5a" as Address,
    "feeTier": 10000
  },
  {
    "symbol": "INTC",
    "name": "Intel",
    "token": "0xc72b96e0E48ecd4DC75E1e45396e26300BC39681" as Address,
    "decimals": 18,
    "pool": "0x2e5a92f5013a64661a49312111be2e8abd33f56a" as Address,
    "feeTier": 3000
  },
  {
    "symbol": "GOOGL",
    "name": "Alphabet Class A",
    "token": "0x2e0847E8910a9732eB3fb1bb4b70a580ADAD4FE3" as Address,
    "decimals": 18,
    "pool": "0x553e9a453425cd9b90919f317061fbc3794cc57a" as Address,
    "feeTier": 3000
  },
  {
    "symbol": "ASML",
    "name": "ASML Holding NV",
    "token": "0x47F93d52cBeC7C6D2CfC080e154002370a60dAEA" as Address,
    "decimals": 18,
    "pool": "0xedb22516b14eb2d1c86927db373b0e8bf70f5cd1" as Address,
    "feeTier": 10000
  },
  {
    "symbol": "AMZN",
    "name": "Amazon",
    "token": "0x12f190a9F9d7D37a250758b26824B97CE941bF54" as Address,
    "decimals": 18,
    "pool": "0x8ac92da74ab5f3b1d024dc1943ad7e15dc4179ef" as Address,
    "feeTier": 3000
  },
  {
    "symbol": "MSTR",
    "name": "Strategy Inc.",
    "token": "0xec262a75e413fAfD0dF80480274532C79D42da09" as Address,
    "decimals": 18,
    "pool": "0x17578c0e0d15da44f31677263114f71ae76653ea" as Address,
    "feeTier": 10000
  },
  {
    "symbol": "PLTR",
    "name": "Palantir Technologies",
    "token": "0x894E1EC2D74FFE5AEF8Dc8A9e84686acCB964F2A" as Address,
    "decimals": 18,
    "pool": "0x851680416a4f4e1c463d45171d61acddbc8554c0" as Address,
    "feeTier": 3000
  },
  {
    "symbol": "RBLX",
    "name": "Roblox",
    "token": "0xF0C4BF4C582cb3836e98394b1d4e7B7281101bE8" as Address,
    "decimals": 18,
    "pool": "0x2ef5945cd5664876b6481fdacfaa2942995a4da8" as Address,
    "feeTier": 10000
  }
];

export const bySymbol = new Map(TRADABLE.map((t) => [t.symbol, t]));
export const byToken = new Map(TRADABLE.map((t) => [t.token.toLowerCase(), t]));
